AUTH0_OAUTH_CLIENT_DOMAIN = "dev-w2v52ay3bjjrf8hm.us.auth0.com"
AUTH0_OAUTH_CLIENT_ID = "0tDc9jxR14eg0kJ6n0rKQXodSZU1vZFb"
AUTH0_OAUTH_CLIENT_SECRET = "GoixUqb6KdR24edK-2_m_o_f2hPvmllqK-XD5yLvqS57QiZFsCsG3MQioJzCEGvg"
